FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r /tmp/requirements.txt
